on:
  push:
    tags:
      - v*

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Prepare
        id: prepare
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            TAG=${GITHUB_REF#refs/heads/}
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          else
            TAG=$GITHUB_REF
          fi

          echo "::set-output name=tag::${TAG}"

      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.prepare.outputs.tag }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
